/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Student;
import utility.DatabaseConnector;
import utility.Validations;

/**
 *
 * @author luole
 */
public class FormJPanel extends javax.swing.JPanel {

    private JPanel bottomPanel;

    /**
     * Creates new form FormJPane
     */
    public FormJPanel() {
        initComponents();
    }

    public FormJPanel(JPanel panel) {
        initComponents();

        this.bottomPanel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collegeButtonGroup = new javax.swing.ButtonGroup();
        firstNameTextfield = new javax.swing.JTextField();
        registrationLabel1 = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        COSRadioButton = new javax.swing.JRadioButton();
        COERadioButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        phoneNumberLabel = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedTextField = new javax.swing.JFormattedTextField();
        hobbyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea = new javax.swing.JTextArea();
        continentLabel = new javax.swing.JLabel();
        continentComboBox = new javax.swing.JComboBox<>();
        photoLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));

        firstNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextfieldActionPerformed(evt);
            }
        });

        registrationLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registrationLabel1.setText("User Registration Form");

        genderLabel.setText("College:");

        ageLabel.setText("Age:");

        NameLabel.setText("Name :");

        collegeButtonGroup.add(COSRadioButton);
        COSRadioButton.setText("COS");
        COSRadioButton.setActionCommand(" COS");
        COSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COSRadioButtonActionPerformed(evt);
            }
        });

        collegeButtonGroup.add(COERadioButton);
        COERadioButton.setText("COE");
        COERadioButton.setActionCommand(" COE");
        COERadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COERadioButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        phoneNumberLabel.setText("Phone Number:");

        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, null, 120, 1));

        try {
            phoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedTextField.setToolTipText("123-456-7890");

        hobbyLabel.setText("Experience");

        hobbyTextArea.setColumns(20);
        hobbyTextArea.setRows(5);
        jScrollPane1.setViewportView(hobbyTextArea);

        continentLabel.setText("Continent:");

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Africa", "North America", "South America", "Antarctica", "Europe", "Australia " }));
        continentComboBox.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLabel)
                    .addComponent(phoneNumberLabel)
                    .addComponent(genderLabel)
                    .addComponent(hobbyLabel)
                    .addComponent(continentLabel)
                    .addComponent(NameLabel))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COSRadioButton)
                    .addComponent(phoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COERadioButton)
                    .addComponent(photoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(registrationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(firstNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(COERadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(COSRadioButton)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(continentLabel)
                            .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hobbyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(photoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextfieldActionPerformed

    private void COSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COSRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COSRadioButtonActionPerformed

    private void COERadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COERadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COERadioButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Declare Variables from user input
            String name;
            String college;
            int age;
            String phoneNumber;
            String continent = "";
            String experience;

            // Extract and Store user data
            name = firstNameTextfield.getText();
            age = (int) this.ageSpinner.getModel().getValue();
            phoneNumber = this.phoneFormattedTextField.getText();
            experience = (String) this.hobbyTextArea.getText();

            // Get gender from radio button group
            if (collegeButtonGroup.getSelection() != null) {
                college = collegeButtonGroup.getSelection().getActionCommand();
            } else {
                college = null;
            }

            if (continentComboBox.getSelectedIndex() != -1) {
                continent = (String) continentComboBox.getSelectedItem();
            }
            
            
            String validationResult = Validations.validateStudentForm(name, age, college, phoneNumber, continent, experience);
            
            if (validationResult !=null){
                  JOptionPane.showMessageDialog(this, validationResult, "Ooops!", JOptionPane.ERROR_MESSAGE);
                  return;
            }
      



            //creat Student object
            Student user = new Student(name, age, college, phoneNumber, continent, experience);
            

            // Add adata tp database
            DatabaseConnector.addUser(user);
            
            
            //show success message
            JOptionPane.showMessageDialog(this, user.toString(), "Success!", JOptionPane.INFORMATION_MESSAGE);
            

            // Navigate to submission view page
            // Create object of type ViewJPanel
            ViewJPanel viewJPanelObject = new ViewJPanel();

            // Add viewPanelObject to the bottomPanel
            this.bottomPanel.add(viewJPanelObject);

            // Navigate to the next page (view Page)
            CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
            layout.next(this.bottomPanel);

        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Ooops!", JOptionPane.ERROR_MESSAGE);
            // System.out.println("Error: " + e.getMessage());
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton COERadioButton;
    private javax.swing.JRadioButton COSRadioButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.ButtonGroup collegeButtonGroup;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JLabel continentLabel;
    private javax.swing.JTextField firstNameTextfield;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobbyLabel;
    private javax.swing.JTextArea hobbyTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField phoneFormattedTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel photoLabel2;
    private javax.swing.JLabel registrationLabel1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
